name: bss_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2  # This matches your working version

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.3.0
  file_picker: ^10.1.2  # Use this newer version that worked before
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # This matches your working version

flutter:
  uses-material-design: true